spring:
  application:
    name: registration-service   # must match config-repo file
  profiles:
    active: dev                  # ðŸ‘ˆ environment (dev / test / prod)
  config:
    import: configserver:http://localhost:8888
