server:
  port: 8888   # Default port for Config Server

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Banti067/Centralized-Configuration-Server.git   # üîÅ Your config repo
          default-label: main                                                     # branch name
          clone-on-start: true                                                    # clone at startup
          search-paths: microservice-system-demo-config                           # folder inside repo (optional)